### ISSUE TITLE
Issue with the make file on Manjaro 21.1.2 GNOME

### ISSUE THREAD

**Issue by tvaeyens** [basaran/easystroke-patched#1]
I have installed the build-dependencies for my distribution with:

`pacman -S boost-libs xorg-server-devel`

When I run the make command, I get the following error:

`In file included from actiondb.cc:16:
actiondb.h:21:10: fatal error: boost/serialization/access.hpp: No such file or directory
   21 | #include <boost/serialization/access.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by basaran** [comment]
did you check if `boost` was also installed?

**Comment by tvaeyens** [comment]
➜  ~ pacman -Qss boost
local/boost-libs 1.76.0-1
    Free peer-reviewed portable C++ source libraries (runtime libraries)

➜  ~ cd /usr/include/boost         
cd: no such file or directory: /usr/include/boost

The directory you mention does not seem to exist

**Comment by tvaeyens** [comment]
I installed boost using `pacman -S boost` and now everything is working, thank you!

**Comment by tvaeyens** [comment]
I installed boost using `pacman -S boost` and now everything is working, thank you!
